language: ruby

rvm:
  - 2.2.2

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - GH_REF="github.com/haganbmj/obs-websocket-js"

before_script:
  - nvm install node
  - npm install npm -g
  - npm install json greenkeeper-lockfile@1 -g
  - bash ./.travis/pre-build.sh
  - npm prune
  - npm install
  - greenkeeper-lockfile-update

script:
  - npm test
  - npm run build
  - bash ./.travis/gh-pages.sh

after_success:
  - npm run node-coveralls
  - greenkeeper-lockfile-upload

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
