language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - GH_REF="github.com/haganbmj/obs-websocket-js"
    - secure: OKVIJmaB5fvaHBUdaUcTimlj7P1PsxuIcGPeTP5STE6o/ERMY3eH97MZxUdcB1LfL2IGyRsg3ye3YL0k6cvySI5+2y47hRRx//WmmX1yXfOuPSbpQNgvSWHaYyabuLkHt4uBp0eSeO4KjAcmv3MIm/9GBJaU7vXI0Y5Y2OcTMApo/TzQbzOpTHNWNPjO4BwFdVIBmT2JzcqTQ8A5PCgeIk8ehwaB3J1+O0AO6bMPIlKuSYR6TYXYTUmKzmXnej8+AjS8ncaCFC9JEfqBx3bwB6bF8AVo/Bdg86X1U5yiQkyG4ShbFfzoGW4dlo8OiVN6ho11T4iReOgi0p/3CL9r4xfV1WVVBrk+R462wyUGQLIMtg/G1k0o8eHhOdI0kxmnTVjZ4GICP7mPRPD79luzTrM5Bi43S+kNn6OfET1/vT+DN3vLmVktIP2oRWtuVr7HpOapw6omSFFbRe/MCSUibuORJb8EDNCbLiARECD46TxQi8IotrUGlAP/E7lObNfKwT1Z0sqo7XT+Cr1fcQmAhknagSe+v47XrVMqXqth5IrcKxa+zjCgaYTB7DkeCdZ9vxjwssljkSdGvKuX37l2RA/p3oaBHmD8nUDHrz4Ku2t4/F3na2LaK7L59pKweVER4FVPtpTeHGbsPwRMlaNMzImVWZnuIyUR3y3mYUz40tQ=

before_script:
  - npm prune
  - npm install json -g
  - bash ./.travis/pre-build.sh

script:
  - npm run build
  - bash ./.travis/gh-pages.sh

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
