language: ruby

rvm:
  - 2.2.2

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - GH_REF="github.com/haganbmj/obs-websocket-js"
    - DEBUG="obs-websocket-js:*"

before_script:
  - nvm install node
  - npm install json -g
  - bash ./.travis/pre-build.sh
  - npm install

script:
  - npm test
  - npm run build

after_success:
  - bash ./.travis/gh-pages.sh
  - npm run node-coveralls

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
