language: ruby

rvm:
  - 2.2.2

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - GH_REF="github.com/haganbmj/obs-websocket-js"

before_script:
  - nvm install v4
  - npm install json -g
  - bash ./.travis/pre-build.sh
  - npm install

script:
  - npm test
  - npm run build
  - bash ./.travis/gh-pages.sh

after_success:
  - npm run node-coveralls
  - bash ./.travis/update-api.sh

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
