language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
before_script:
  - npm prune
  # - npm install json semver -g
  # - bash ./.scripts/pre-build.sh
script:
  - npm run build
  # - bash ./.scripts/travis-gh-pages.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
